# Generated by Django 6.0.4 on 2026-04-21 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_type', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('side', 'Side')], default='front', max_length=10)),
                ('base_image', models.ImageField(upload_to='products/base_images/')),
                ('displacement_map_x', models.FileField(blank=True, null=True, upload_to='products/maps/')),
                ('displacement_map_y', models.FileField(blank=True, null=True, upload_to='products/maps/')),
                ('shadow_map', models.ImageField(blank=True, null=True, upload_to='products/maps/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='PrintArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(help_text='X coordinate of top-left corner')),
                ('y', models.IntegerField(help_text='Y coordinate of top-left corner')),
                ('width', models.IntegerField(help_text='Maximum width of the print area')),
                ('height', models.IntegerField(help_text='Maximum height of the print area')),
                ('product_view', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_area', to='catalog.productview')),
            ],
        ),
    ]
