# Generated by Django 6.0.4 on 2026-04-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrintArea',
        ),
    ]
