# Generated by Django 6.0.4 on 2026-04-21 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_delete_printarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(help_text='X coordinate of top-left corner')),
                ('y', models.IntegerField(help_text='Y coordinate of top-left corner')),
                ('width', models.IntegerField(help_text='Maximum width of the print area')),
                ('height', models.IntegerField(help_text='Maximum height of the print area')),
                ('product_view', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_area', to='catalog.productview')),
            ],
        ),
    ]
